version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: unsafepassword
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - '.:/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq
    volumes:
      - '.:/myapp'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  
